[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "GGqt2oJWPH1oXoxXndNEVaWxKv5nTNZtUDosK1pFVXTm"

# [programs.devnet]
# contract = "GGqt2oJWPH1oXoxXndNEVaWxKv5nTNZtUDosK1pFVXTm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/degencodebeast/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
